# Generated by Django 4.1.7 on 2023-03-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='jobtitle',
        ),
    ]
