# Generated by Django 4.1.7 on 2023-03-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_title_job_jobtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jobtitle',
            new_name='title',
        ),
    ]
